#!/usr/bin/env bash
#
# sync-from-core.sh — regenerate the skill's catalogue + schema references
# from the pinned codeup-cli submodule.
#
# The skill is single-sourced: it never hand-maintains the 107-pattern
# catalogue or the .codeup/ schema. Those live in codeup-cli; here we copy
# them VERBATIM so the skill's findings agree byte-for-byte with what the
# CLI and the VS Code extension produce. The host LLM reads the YAML/MD
# directly — no transformation, no drift.
#
# To bump the catalogue version:
#   git -C vendor/codeup-cli fetch --tags
#   git -C vendor/codeup-cli checkout vX.Y.Z
#   ./scripts/sync-from-core.sh
#   git add vendor/codeup-cli references/ .pinned-version
#   git commit -m "sync catalogue from codeup-cli vX.Y.Z"
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SUB="$ROOT/vendor/codeup-cli"
CAT_SRC="$SUB/crates/codeup-core/resources/default.yaml"
SCHEMA_SRC="$SUB/SCHEMA.md"

if [[ ! -f "$CAT_SRC" || ! -f "$SCHEMA_SRC" ]]; then
  echo "error: submodule not checked out. Run: git submodule update --init" >&2
  exit 1
fi

cp "$CAT_SRC" "$ROOT/references/catalogue.yaml"
cp "$SCHEMA_SRC" "$ROOT/references/schema.md"

# Record exactly what we pinned, so the provenance is auditable and the
# checksums catch any accidental edit to the generated references.
VERSION="$(git -C "$SUB" describe --tags --always)"
COMMIT="$(git -C "$SUB" rev-parse HEAD)"
CAT_SHA="$(shasum -a 256 "$ROOT/references/catalogue.yaml" | cut -d' ' -f1)"
SCHEMA_SHA="$(shasum -a 256 "$ROOT/references/schema.md" | cut -d' ' -f1)"
PATTERN_COUNT="$(grep -c '^  - id:' "$ROOT/references/catalogue.yaml")"

cat > "$ROOT/.pinned-version" <<EOF
# Provenance of references/ — generated by scripts/sync-from-core.sh. Do not edit by hand.
source_repo:    https://github.com/johncoleman-thoughtworks/codeup-cli
pinned_version: $VERSION
pinned_commit:  $COMMIT
pattern_count:  $PATTERN_COUNT
catalogue_sha256: $CAT_SHA
schema_sha256:    $SCHEMA_SHA
EOF

echo "Synced references/ from codeup-cli $VERSION ($PATTERN_COUNT patterns)."
echo "  references/catalogue.yaml  $CAT_SHA"
echo "  references/schema.md       $SCHEMA_SHA"
